services:
  postgres:
    image: postgres:16
    container_name: studyapp_postgres_dev
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      # postgres_data: docker volumes 
      # /var/lib/postgresql/data: postgres data folder in container

  mongodb:
    image: mongo:8.0
    container_name: studyapp_mongodb_dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data: